language: go
go:
- "1.10.x"
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - develop
  - master
install:
  - env GO111MODULE=on go get github.com/stretchr/testify/assert
  - env GO111MODULE=on go get github.com/stretchr/testify/require
